my_list = []
print("Step 1:", my_list)
my_list.append(10)
my_list.append(20)  
my_list.append(30) 
my_list.append(40)
print("Step 2:", my_list)
my_list.insert(1, 15)
print("Step 3:", my_list)
my_list.extend([50, 60, 70])
print("Step 4:", my_list)
my_list.pop()  
print("Step 5:", my_list)
my_list.sort()
print("Step 6:", my_list)
index_of_30 = my_list.index(30)  
print("Step 7:", index_of_30)
print("Final Sorted List:", my_list)
print("Index of 30:", index_of_30)
